/*
 * action types
 */

export const TURN_ACTIONS = {
  SET_MOVE_PATH: 'SET_MOVE_PATH',
  CANCEL_MOVE: 'CANCEL_MOVE', // this should probably also be state
  CONFIRM_ATTACK: 'CONFIRM_ATTACK',
  SET_ATTACK: 'SET_ATTACK',
  TOGGLE_ATTACK_RANGE: 'TOGGLE_ATTACK_RANGE',
  FINISH_TURN: 'FINISH_TURN',
  CLICK_TILE: 'CLICK_TILE',
  SET_MOVE_SQUARES: 'SET_MOVE_SQUARES',
  SET_ACTIVE_UNIT_MOVED: 'SET_ACTIVE_UNIT_MOVED',
  SET_PF_ARR: 'SET_PF_ARR',
  SET_ATTACK_SQUARES: 'SET_ATTACK_SQUARES',
  SET_ATTACK_TARGET: 'SET_ATTACK_TARGET',
  FINISH_UNIT: 'FINISH_UNIT'
}

export const UNIT_ACTIONS = {
  MOVE_UNIT: 'MOVE_UNIT',
  FINISH_UNIT: 'FINISH_UNIT',
  RESOLVE_ATTACK: 'RESOLVE_ATTACK',
  SET_ACTIVE_UNIT: 'SET_ACTIVE_UNIT',
  SYNC_UNITS: 'SYNC_UNITS',
  UPDATE_UNIT: 'UPDATE_UNIT'
}
